### ISSUE TITLE
Create a condition that prevents obstacles from spawning too soon 

### ISSUE THREAD

**Issue by abbiehuynh** [abbiehuynh/techtonica-projects#12]
Currently, in my cat escape game, the trash can obstacles are set to randomly spawn at a random time within 4 seconds. 
However, sometimes, the trashcans spawn too quickly, making it impossible for the cat to jump in time for the next obstacle to appear. (I have the jump function set to not allow double jumping/only jump when not jumping)

I need to add a condition that prevents obstacles from spawning too early, allowing the cat to land and have time to jump before hitting the next obstacle. This will allow the player to have a fair chance of continuing the game. 

https://github.com/abbiehuynh/techtonica-projects/blob/cd965fe384bd0b6cac8c98b2eacefa8c495cad0e/js-html-games/app.js#L76-L77

[cat escape](https://github.com/abbiehuynh/techtonica-projects/tree/cd965fe384bd0b6cac8c98b2eacefa8c495cad0e/js-html-games)

**Comment by tati-guzman** [comment]
Hi Abbie, can I claim this issue? I'd love to work on it!

**Comment by abbiehuynh** [comment]
Hi Tati, I am assigning this issue to you, Thank you!

**Comment by abbiehuynh** [comment]
Resolved Issue with PR #20 .
